/*
 * This file is generated by jOOQ.
 */
package org.example.jooqspring.db;


import org.example.jooqspring.db.tables.Author;
import org.example.jooqspring.db.tables.AuthorBook;
import org.example.jooqspring.db.tables.Book;


/**
 * Convenience access to all tables in demo.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>demo.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>demo.author_book</code>.
     */
    public static final AuthorBook AUTHOR_BOOK = AuthorBook.AUTHOR_BOOK;

    /**
     * The table <code>demo.book</code>.
     */
    public static final Book BOOK = Book.BOOK;
}
